<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYvxrdbo\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYvxrdbo/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYvxrdbo.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYvxrdbo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYvxrdbo\appProdProjectContainer([
    'container.build_hash' => 'Yvxrdbo',
    'container.build_id' => 'b1f2d737',
    'container.build_time' => 1636655317,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYvxrdbo');
